language: ruby
cache: bundler
sudo: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssl

rvm:
  - 2.1.7
addons:
  apt:
    packages:
    - libgeoip-dev
    - libgeoip1
script: openssl version && bundle exec rspec spec
